# Basic dependabot.yml file

version: 2
updates:
    # Enable version updates for npm
    - package-ecosystem: 'npm'
      # Look for `package.json` and `lock` files in the `root` directory
      directory: '/'
      # Max PRs open at teh same time
      open-pull-requests-limit: 10
      # Check the npm registry for updates every day (weekdays)
      schedule:
          interval: 'daily'

      commit-message:
          # Prefix all commit messages with "npm"
          prefix: '[BOT] ⬆ npm'
          # include a list of updated dependencies
          include: 'scope'

    - package-ecosystem: 'gitsubmodule'
      directory: '/'
      schedule:
          interval: 'daily'
      commit-message:
          # Prefix all commit messages with "npm"
          prefix: '[BOT] ⬆ sub'
          # include a list of updated dependencies
          include: 'scope'
