CI:
    - '.github/workflows/*'
    - '.circleci/*'

Config:
    - 'config/*'

Dependencies:
    - 'package.json'
    - 'package-lock.json'

Docs:
    - 'CONTRIBUTING.md'
    - '**/README.md'
    - 'docs/*'

Tooling:
    - 'tools/**/*'
