ci:
    - '.github/workflows/*'
    - '.circleci/*'

config:
    - 'config/*'

dependencies:
    - 'package.json'
    - 'package-lock.json'

documentation:
    - 'CONTRIBUTING.md'
    - '**/README.md'
    - 'docs/*'

source:
    - 'src/**/*'

tooling:
    - 'tools/**/*'
