name: main - Pre-release to npmjs
on:
  push:
    branches:
      - main

jobs:

  tests:
    name: 'Run Tests'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:ci

  publish:
    name: 'Publish on npm'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Production Build
        run: npm run build

      - name: Publish to NPM
        run: npm ci && npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    needs: [ tests ]

  upload-release:
    name: 'Upload release on GH'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Release Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: "Upload Release"
        uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "v${{ steps.package-version.outputs.current-version}}"
          draft: true
          prerelease: true
          target_commitish: ${{ github.sha }}
    needs: [ publish ]
