name: PR - Tests

on:
  pull_request:
    branches:
      - main

permissions:
  actions: write
  checks: write
  contents: read
  deployments: read
  id-token: write
  issues: read
  discussions: write
  packages: read
  pages: write
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        id: tests
        run: |
          echo "### Running tests ! :rocket:" >> $GITHUB_STEP_SUMMARY
          npm run test:ci 2>&1 | tee output.txt
          echo "test_output<<EOF" >> $GITHUB_ENV
          cat output.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./coverage/lcov.info

      - name: Create comment about tests
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Tests output
            ```
            ${{ env.test_output }}
            ```
          edit-mode: replace
